#%RAML 1.0
title: currency-conversion-sapi 
version: v1
mediaType: application/json



/exchange:
  get:
    description: Get exchange rate

    responses:
      200:
        body:
          application/json:
            example: !include example/currency-conversion-respone.json